# Generated by Django 5.1.2 on 2024-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback',
            field=models.CharField(max_length=160),
        ),
    ]
